version: '2'
services:
    # mongodb
    mongodb:
      image: mongo:4.4.6
      container_name: aura_mongodb_1
      ports:
          - 27018:27017
      environment:
          - MONGO_INITDB_DATABASE=edunet
          - MONGO_INITDB_ROOT_USERNAME=admin
          - MONGO_INITDB_ROOT_PASSWORD=admin
      volumes:
          - ./mongodb/data:/data/db
      networks:
        - edunet
networks:
  edunet:
    driver: bridge